name: Instigate docs build

on:
  push:
    branches: [main]
    paths:
      - README.adoc
      - _docs
      - lib/asciidocsy/data
  pull_request:
    paths:
      - README.adoc
      - _docs
      - lib/asciidocsy/data

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: ping the docs repo
        env:
          GITHUB_TOKEN: ${{ secrets.DOCS_DEPLOY_TOKEN }}
          EVENT: instigate-deploy
          ORG: docops
          REPO: asciidocsy-docs-www
          REF: ${{ github.ref }}
        run: |
          curl -d "{\"event_type\": \"${EVENT}\"}, \"client_payload\": {\"ref\": \"${REF}\"}}" -H "Content-Type: application/json" -H "Authorization: token ${GITHUB_TOKEN}" -H "Accept: application/vnd.github.everest-preview+json" "https://api.github.com/repos/${ORG}/${REPO}/dispatches"
